### ISSUE TITLE
Release linked with Debug version of cpprestsdk

### ISSUE THREAD

**Issue by kreuzerkrieg** [SignalR/SignalR-Client-Cpp#160] opened 2017-01-18 14:06 UTC
Hi,
Your nuget package includes win32 release version of signalr linked with debug version of cpprestsdk. Please fix.

packages\Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta1\build\native\dll\Win32\v140\Release\
dependency walker screen.
![screen](https://cloud.githubusercontent.com/assets/829317/22066936/d65141ac-dd97-11e6-9999-c348d7ce968f.png)
packages.config
```
<packages>
  <package id="cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn" version="2.7.0" targetFramework="native" />
  <package id="Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop" version="1.0.0-beta1" targetFramework="native" />
</packages>

```

**Comment by moozzyk** [comment] 2017-01-18 17:34
Thanks for the report. This is a dupe of https://github.com/aspnet/SignalR-Client-Cpp/issues/142. It was fixed but the new version of the package is not on NuGet yet. If you need a fix for this you can get the latest package from this feed: https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json (link to the gallery: https://dotnet.myget.org/gallery/aspnetcore-ci-dev)

**Closed as completed by moozzyk** 2017-01-18 17:34 UTC
Labels: bug, duplicate

**Comment by kreuzerkrieg** [comment] 2017-01-18 17:36
Thanks!
